<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WFM.Domain\WFM.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Employees\" />
    <Folder Include="Features\Attendance\" />
    <Folder Include="Features\Tasks\" />
    <Folder Include="Common\" />
  </ItemGroup>

</Project>
